export enum Paths {
  Home = '/',
  MainMenu = 'mainMenu',
  BodySystems = 'bodySystems',
  Procedures = 'procedures',
  Sensory = 'sensory',
  Skeletal = 'skeletal',
  Muscular = 'muscular',
  Nervous = 'nervous',
  Digestive = 'digestive',
  Cardiovascular = 'cardiovascular',
  Smell = 'smell',
  Hearing = 'hearing',
  Proprioception = 'proprioception',
  Sight = 'sight',
  Taste = 'taste',
  Touch = 'touch',
  Vestibular = 'vestibular',
  Eeg = 'eeg',
  Iv = 'iv',
  Mri = 'mri',
  SurgicalPrep = 'surgicalPrep',
  Wellness = 'wellness',
  XRay = 'xRay',
  Game = 'game',
}

export type PathKeys = keyof typeof Paths;
